# Generated by Django 4.0.3 on 2022-03-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifieduser',
            name='phone_num',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
