# Generated by Django 4.0.3 on 2022-03-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_modifieduser_phone_num'),
        ('restaurants', '0004_alter_restaurant_followers_alter_restaurant_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='restaurant_followers', to='accounts.modifieduser'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='restaurant_likes', to='accounts.modifieduser'),
        ),
    ]
