# Generated by Django 4.0.3 on 2022-03-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_modifieduser_phone_num'),
        ('restaurants', '0003_alter_comment_restaurant_alter_comment_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='followers',
            field=models.ManyToManyField(related_name='restaurant_followers', to='accounts.modifieduser'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='likes',
            field=models.ManyToManyField(related_name='restaurant_likes', to='accounts.modifieduser'),
        ),
    ]
