# Generated by Django 4.0.3 on 2022-03-06 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_alter_blog_likes_alter_comment_restaurant_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModifiedUser',
        ),
    ]
