# Generated by Django 4.0.3 on 2022-03-05 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_menuitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='restaurants.blog'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='restaurants.modifieduser'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='restaurant_followers', to='restaurants.modifieduser'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='restaurant_likes', to='restaurants.modifieduser'),
        ),
    ]
