# Generated by Django 4.0.3 on 2022-03-14 16:58

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_alter_restaurant_followers_alter_restaurant_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='phone_num',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
