# Generated by Django 4.0.3 on 2022-03-06 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
        ('restaurants', '0005_alter_blog_likes_alter_comment_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(related_name='blog_likes', to='accounts.modifieduser'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='accounts.modifieduser'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='accounts.modifieduser'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='accounts.modifieduser'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.modifieduser'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='restaurant_followers', to='accounts.modifieduser'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='restaurant_likes', to='accounts.modifieduser'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_owner', to='accounts.modifieduser'),
        ),
    ]
