# Generated by Django 4.0.3 on 2022-03-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_alter_restaurant_phone_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='contents',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='publish_timestamp',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
