# Generated by Django 4.0.3 on 2022-03-15 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_comment_contents_alter_blog_publish_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_img', models.ImageField(blank=True, null=True, upload_to='restaurant_pics/')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_images', to='restaurants.restaurant')),
            ],
        ),
    ]
