# Generated by Django 4.0.3 on 2022-03-06 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='restaurants.restaurant'),
        ),
    ]
