# Generated by Django 4.0.3 on 2022-03-06 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_notification_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_notifications', to='restaurants.restaurant'),
        ),
    ]
