# Generated by Django 4.0.3 on 2022-03-06 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_alter_notification_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
