# Generated by Django 4.0.3 on 2022-03-06 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
        ('restaurants', '0010_remove_notification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='redirection',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.modifieduser'),
            preserve_default=False,
        ),
    ]
