# Generated by Django 4.0.3 on 2022-03-07 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_remove_notification_redirection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='comment',
        ),
    ]
