# Generated by Django 4.0.3 on 2022-03-07 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_remove_restaurant_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='blog',
        ),
        migrations.AddField(
            model_name='blog',
            name='restaurant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='restaurants.restaurant'),
            preserve_default=False,
        ),
    ]
